### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCGeneral.cpp:70

### ISSUE THREAD

**Issue by struggling-man** [OdingdongO/pytorch_classification#1]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCGeneral.cpp line=70 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "/home/es/PycharmProjects/untitled1/baidu/train_baidu_xjtu.py", line 67, in <module>
    model = model.cuda()
  File "/home/es/sky/environment/python/anaconda3/envs/pytorch_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/es/sky/environment/python/anaconda3/envs/pytorch_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/home/es/sky/environment/python/anaconda3/envs/pytorch_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/home/es/sky/environment/python/anaconda3/envs/pytorch_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCGeneral.cpp:70

求大佬带。是安装了cuda8.0，看这个错误好像是无法调用cuda。

**Comment by WilyZhao8** [comment]
这个应该是你的GPU ID没有设置对，这个工程里面的os.environ["CUDA_VISIBLE_DEVICES"]=3默认为3，需要修改一下，如果一块GPU，就改为0

**Comment by struggling-man** [comment]
十分感谢就是这个原因
